#!/bin/bash
filename="./video/Time and Stress Managment Lessons.mp4"
ffmpeg -i "$filename" -ss 172 -t 04 "Time and Stress Managment Lessons - Lesson 1.mp4"
ffmpeg -i "$filename" -ss 177 -t 24 "Time and Stress Managment Lessons - Lesson 2.mp4"
ffmpeg -i "$filename" -ss 391 -t 215 "Time and Stress Managment Lessons - Lesson 3.mp4"
ffmpeg -i "$filename" -ss 1075 -t 15 "Time and Stress Managment Lessons - Lesson 4.mp4"
ffmpeg -i "$filename" -ss 1147 -t 12 "Time and Stress Managment Lessons - Lesson 5.mp4"
ffmpeg -i "$filename" -ss 1147 -t 13 "Time and Stress Managment Lessons - Lesson 6.mp4"
ffmpeg -i "$filename" -ss 1160 -t 19 "Time and Stress Managment Lessons - Lesson 7.mp4"
ffmpeg -i "$filename" -ss 1186 -t 14 "Time and Stress Managment Lessons - Lesson 8.mp4"
ffmpeg -i "$filename" -ss 1208 -t 32 "Time and Stress Managment Lessons - Lesson 9.mp4"
ffmpeg -i "$filename" -ss 1248 -t 5 "Time and Stress Managment Lessons - Lesson 10.mp4"
ffmpeg -i "$filename" -ss 1280 -t 11 "Time and Stress Managment Lessons - Lesson 11.mp4"
ffmpeg -i "$filename" -ss 1347 -t 19 "Time and Stress Managment Lessons - Lesson 12.mp4"
ffmpeg -i "$filename" -ss 1408 -t 2 "Time and Stress Managment Lessons - Lesson 13.mp4"
ffmpeg -i "$filename" -ss 1458 -t 34 "Time and Stress Managment Lessons - Lesson 14.mp4"
ffmpeg -i "$filename" -ss 1530 -t 15 "Time and Stress Managment Lessons - Lesson 15.mp4"
ffmpeg -i "$filename" -ss 1555 -t 10 "Time and Stress Managment Lessons - Lesson 16.mp4"
ffmpeg -i "$filename" -ss 1568 -t 9 "Time and Stress Managment Lessons - Lesson 17.mp4"
ffmpeg -i "$filename" -ss 1770 -t 9 "Time and Stress Managment Lessons - Lesson 18.mp4"
ffmpeg -i "$filename" -ss 1787 -t 35 "Time and Stress Managment Lessons - Lesson 19.mp4"
ffmpeg -i "$filename" -ss 1828 -t 8 "Time and Stress Managment Lessons - Lesson 20.mp4"