#!/bin/bash
filename="./video/Developing Operational Plans.mp4"
ffmpeg -i "$filename" -ss 114 -t 6 "Developing Operational Plans - Lesson 1.mp4"
ffmpeg -i "$filename" -ss 131 -t 26 "Developing Operational Plans - Lesson 2.mp4"
ffmpeg -i "$filename" -ss 265 -t 35 "Developing Operational Plans - Lesson 3.mp4"
ffmpeg -i "$filename" -ss 299 -t 44 "Developing Operational Plans - Lesson 4.mp4"
ffmpeg -i "$filename" -ss 371 -t 12 "Developing Operational Plans - Lesson 5.mp4"
ffmpeg -i "$filename" -ss 379 -t 4 "Developing Operational Plans - Lesson 6.mp4"
ffmpeg -i "$filename" -ss 485 -t 28 "Developing Operational Plans - Lesson 7.mp4"
ffmpeg -i "$filename" -ss 598 -t 13 "Developing Operational Plans - Lesson 8.mp4"
ffmpeg -i "$filename" -ss 709 -t 31 "Developing Operational Plans - Lesson 9.mp4"
ffmpeg -i "$filename" -ss 741 -t 20 "Developing Operational Plans - Lesson 10.mp4"
ffmpeg -i "$filename" -ss 761 -t 9 "Developing Operational Plans - Lesson 11.mp4"
ffmpeg -i "$filename" -ss 787 -t 13 "Developing Operational Plans - Lesson 12.mp4"
ffmpeg -i "$filename" -ss 944 -t 6 "Developing Operational Plans - Lesson 13.mp4"
ffmpeg -i "$filename" -ss 962 -t 8 "Developing Operational Plans - Lesson 14.mp4"
ffmpeg -i "$filename" -ss 1031 -t 20 "Developing Operational Plans - Lesson 15.mp4"
ffmpeg -i "$filename" -ss 1052 -t 31 "Developing Operational Plans - Lesson 16.mp4"
ffmpeg -i "$filename" -ss 1202 -t 21 "Developing Operational Plans - Lesson 17.mp4"
ffmpeg -i "$filename" -ss 1225 -t 19 "Developing Operational Plans - Lesson 18.mp4"
ffmpeg -i "$filename" -ss 1349 -t 9 "Developing Operational Plans - Lesson 19.mp4"
ffmpeg -i "$filename" -ss 1380 -t 20 "Developing Operational Plans - Lesson 20.mp4"